lawIsMoney/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from web import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^web/', include('web.urls'))
]

web/urls.py
from django.conf.urls import url
from . import views

app_name = 'web'
urlpatterns = [
    url(r'^index/$', views.Index, name='index'),
    url(r'^about/$', views.About, name='about'),
    url(r'^archive/$', views.archive, name='archive'),
    url(r'^link/$', views.Link, name='link'),
    url(r'^message/$', views.Message, name='message'),
    url(r'^article/(?P<pk>\d+)$', views.Articles, name='article'),
    url(r'^get_comment/$', views.GetComment, name='get_comment'),
    url(r'^detail/(?P<pk>\d+)$', views.detail, name='detail'),
    url(r'^search/$', views.search, name='search'),
    url(r'^tag/(?P<name>.*?)$', views.tag, name='tag'),
    url(r'.*?$', views.Index, name='index'),
]

web/templates/backup/about.html
{% extends "web/base.html" %}
{% block content %}
    <section class="mysection" style="animation: fuxiasuo 0.8s;">页面建设中。。。。</section>

{% endblock %}

web/templates/backup/archive.html
{% extends "web/base.html" %}
{% load custom_filter %}
{% block css %}
    <link href="/static/archives/style.css" rel="stylesheet"/>
{% endblock %}

{% block content %}
    <section class="mysection main" style="animation: fuxiasuo 0.8s;">
        <ul class="timeline">
            {% for article in article_list %}
                <li class="event">
                    <input type="radio" name="tl-group" {% if forloop.counter0 == 0 %} checked {% endif %}/>
                    <label></label>
                    <div class="thumb"><span>{{ article.date_time }}</span></div>
                    <div class="content-perspective">
                        <div class="content">
                            <div class="content-inner">
                                <h3><a href="{% url "web:detail" pk=article.id%}">{{ article.title }}</a></h3>
                                <p>{{ article.digest }}</p>
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </section>
{% endblock %}

web/templates/backup/articles.html
{% extends "web/base.html" %}
{% load custom_filter %}
{% block content %}
    {% paginate article_list 8 %}
    {% if article_list %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "web:article" pk=0 %}"><i class="el-th-list"></i>{% if category %}列表{% else %} 全部 {% endif %} &nbsp;&nbsp;> &nbsp;&nbsp;</a>
            <span class="orange-text">{{ category }}</span>
            <span style="float:right;margin-right:10px;">共有文章:<a class="orange-text"> {{ count }} </a>篇</span>
        </h4>
        <div class="arclist">
            <!--列表开始-->
            <ul>
                {% for article in article_list %}
                    <li {% if article.view > 500 %}id="tuijian"{% elif article.view > 100 %} id="Hot" {% endif %}>
                    <div class="arcimg">

                        <img src="{{ article.picture }}"
                             alt="{{ article.title }}" title="{{ article.title }}"/>
                    </div>
                    <div class="arc-right">
                        <h4 class="blue-text"><a href="{% url "web:detail" pk=article.id %}" title="{{ article.title }}">{{ article.title }}</a></h4>
                        <p>{{ article.digest }}</p>
                        <ul>
                            <li><a title="{{ article.author }} {{ article.date_time }} 发表 "><i class="el-time"></i> {{ article.date_time }}</a></li>
                            <li><a href="#" title="作者： {{ article.author }}"><i class="el-user"></i>{{ article.author }}</a></li>
                            <li><a href="#" title="已有 {{ article.comment }} 条评论"><i class="el-comment"></i>{{ article.comment }}</a>
                            </li>
                            <li><a title="已有 {{ article.view }} 次浏览"><i class="el-eye-open"></i>{{ article.view }}</a></li>
                            <li class="mob-hidden">
                                <i class="el-tag"></i>
                                <a href="#">{{ article.tag.values| getTag }}</a>&nbsp;
                            </li>
                            <li><a href="{% url "web:article" pk=article.category_id %}" title="查看分类"><i class="el-th-list"></i>{{ article.category }}</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <!--列表结束-->
        </div>
        <!--分页-->

        <div class="pagination">
            <div class="list-page">
                <ul class="post-data">
                    <li><a>第 {{ current_page }} - {{ last_page }} 页</a> <a>共 {{ count }} 条</a></li>
                </ul>
            </div>
            <ul>

                <li {% if current_page == 1 %}class="active"{% endif %}><a href="?page=1">首页</a></li>
                <li {% if current_page >= 2 %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:-1 }}">上一页</a></li>
                <li {% if current_page < last_page %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:1 }}">下一页</a></li>
                <li {% if current_page == last_page %}class="active"{% endif %}><a href="?page={{ last_page }}">尾页</a></li>
            </ul>
        </div>

    </section>
    {% else %}
    <section class="mysection" style="animation: fuxiasuo 0.8s;">暂时没有任何文章。</section>
    {% endif %}

{% endblock %}

web/templates/backup/detail.html
{% extends "web/base.html" %}
{% load custom_filter %}

{% block css %}
    <link rel="stylesheet" href="/static/css/markdown.css">
{% endblock %}

{% block content %}

    <section class="mysection">
        <article>
            <h3 class="arc-title index-title">{{ article.title }}</h3>
            <div class="post-line bg-color">
                <ul>
                    <li><a title="{{ article.author }}发表于{{ article.date_time }}"><i class="el-time"></i>
                        <time>{{ article.date_time }}</time>
                    </a></li>
                    <li><a href="#"><i class="el-user"></i>{{ article.author }}</a></li>
                    <li><a href="#Coon" title="转到评论"><i class="el-comment"></i>{{ article.comment }}条</a></li>
                    <li><a title="已有 {{ article.view }} 次浏览"><i class="el-eye-open"></i>{{ article.view }}</a></li>
                </ul>
            </div>

            <!--文章正文-->
            <div class="article-content bg-color markdown-body">
                <div class="post-content" style="padding: 10px 20px 20px 10px">
                    <div class="BlogAnchor" style="text-indent: 20px; font-size: 14px; margin-bottom: 30px">
                        <p>
                            <b id="AnchorContentToggle" title="收起" style="cursor:pointer;">目录[-]</b>
                        </p>
                        <div class="AnchorContent" id="AnchorContent"></div>
                    </div>
                    {{ article.content|custom_markdown }}
                </div>
            </div>
                <!--分享-->
                <div class="article-fx"><a class="fx-btn img-circle" href="javascript:;">分享</a>
                    <div class="bd-fx arc-bdfx">
                        <i class="el-remove fx-close"></i>
                        <ul class="bdsharebuttonbox">
                            <li><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></li>
                            <li><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a></li>
                            <li><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a></li>
                            <li><a href="#" class="bds_tieba" data-cmd="tieba" title="分享到百度贴吧"></a></li>
                        </ul>
                        <script>window._bd_share_config = {
                            "common": {
                                "bdSnsKey": {},
                                "bdText": "",
                                "bdMini": "2",
                                "bdMiniList": false,
                                "bdPic": "",
                                "bdStyle": "1",
                                "bdSize": "32"
                            }, "share": {}
                        };
                        with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];</script>
                    </div>
                </div>
                <!--END 分享-->
                <hr>

                <!--标签-->
                <div class="article_tag">
                    <ul>
                        <li><a href="{% url "web:article" pk=article.category_id %}"
                               title="归类：{{ article.category }}">{{ article.category }}</a></li>
                        {% for tag in article.tag.all %}
                            <li><a href="{% url "web:tag" name=tag.tag_name %}" title="标签：{{ tag.tag_name }} ">{{ tag.tag_name }}</a>&nbsp;</li>
                        {% endfor %}
                    </ul>
                </div>

        </article>

        <!--评论表单-->
        <h3 class="form-btn blue-text"><a href="javascript:;"><i class="el-edit"></i>我要留言 / 展开表单</a></h3>
        <div id="Coon" class="form-zd form-in">
            <div id="cloud-tie-wrapper" class="cloud-tie-wrapper"></div>
            <script>
                var cloudTieConfig = {
                    url: "{{ article.sourceUrl }}",
                    sourceId: "{{ article.id }}",
                    productKey: "0078b35005ba4b3da6403eb8d16b0bcb",
                    target: "cloud-tie-wrapper"
                };
            </script>
            <script src="https://img1.cache.netease.com/f2e/tie/yun/sdk/loader.js"></script>

        </div>
    </section>


{% endblock %}


{% block js %}

    <script>
        function GenerateContentList() {
            $(".post-content").find("h2,h3").each(function (i, item) {
                var tag = $(item).get(0).localName;
                $(item).attr("id", "wow" + i);
                $("#AnchorContent").append('<li><a class="new' + tag + ' anchor-link"  href="#wow' + i + '">' + $(this).text() + '</a></li>');
                $(".newh2").css("margin-left", 0);
                $(".newh3").css("margin-left", 20);
                $(".newh4").css("margin-left", 40);
                $(".newh5").css("margin-left", 60);
                $(".newh6").css("margin-left", 80);
            });
            $("#AnchorContentToggle").click(function () {
                var text = $(this).html();
                if (text == "目录[-]") {
                    $(this).html("目录[+]");
                    $(this).attr({"title": "展开"});
                } else {
                    $(this).html("目录[-]");
                    $(this).attr({"title": "收起"});
                }
                $("#AnchorContent").toggle();
            });
        }
    GenerateContentList()
    </script>
{% endblock %}

web/templates/backup/footer.html
<footer>
    <!--底部导航-->
    <div class="foot-nav">
        <div class="copy-right"><span>CopyRight &#169; 2015-2016 j_hao104's博客 &#160;&#160;&#160;     Design by j_hao104</span></div>
        <div class="license bottom-nav">
            <a href="http://www.miitbeian.gov.cn">@2017 spiderpy.cn 	蜀ICP备17012574号-1</a></span>
        </div>
    </div>
    <div id="toTop">Back to Top</div>
    <script>
    </script>


</footer>

web/templates/backup/header.html
<header class="myheader">
    <div class="top">
        <!--头像左边部分-->
        <div class="top-left">
{#            <div class="logo"><a href="/"><img src="/static/images/logo.gif"/></a></div>#}
                <div class="logo"><a href="#"><img src="/static/images/logo.png"/></a></div>

            <!--滚动消息-->
            <div class="web-xiaoxi">
                <i class="el-speaker"></i>
                <ul class="mulitline">
                    <li>正在最后的优化正在最后的优化正在最后的优化</li>
                    <li>完成后将放出模板</li>
                    <li>完美自适应手机</li>
                </ul>
            </div>
            <!--END 消息 -->

            <!--手机菜单按钮-->
            <div class="mobile-nav"><i class="el-lines"></i><i class="el-remove"></i></div>
        </div>
        <!--电脑导航开始-->
        <nav class="mynav">
            <ul class="orange-text">
                <li class=""><a href="{% url "web:index" %}">首页</a></li>
                <li><a href="{% url "web:about" %}">关于</a></li>
                <li><a href="{% url "web:article" pk=0 %}">博客</a></li>
                <li class='drop'>
                    <a href="JavaScript:;">分类<i class='el-chevron-down'></i></a>
                    <div class="drop-nav orange-text ">
                        <ul>
                            {% for category in category_list %}
                                <li><a href="{% url "web:article" pk=category.pk %}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                <li><a href="{% url "web:archive" %}">归档</a></li>
                <li><a href="{% url "web:link" %}">链接</a></li>
                <li><a href="{% url "web:message" %}">留言</a></li>
            </ul>
        </nav>

        <!--这里是手机导航-->
        <div class="mob-menu">
            <!--手机顶部搜索-->
            <div class="search ">
                <form action="{% url "web:search" %}" method="get">
                    <div class="search-index">
                        <input name="name" type="text" placeholder="请输入关键字" onfocus="this.placeholder=''"
                               onblur="this.placeholder='请输入关键字'"/>
                        <i class="el-search"><input value=" " type="submit"/></i>
                    </div>
                </form>
            </div>
            <!--手机下拉菜单-->
            <ul>
                <li><a href="{% url "web:index" %}">首页</a></li>
                <li><a href="{% url "web:about" %}">关于</a></li>
                <li><a href="{% url "web:article" pk=0 %}">博客</a></li>
                <li class='mob-drop'>
                    <a href="javascrip:;">分类</a>
                    <ul class="mob-dropmenu">
                        {% for category in category_list %}
                            <li><a href="{% url "web:article" pk=category.pk %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li><a href="{% url "web:archive" %}">归档</a></li>
                <li><a href="{% url "web:link" %}">链接</a></li>
                <li><a href="{% url "web:message" %}">留言</a></li>
            </ul>
        </div>
    </div>
    <!--换肤--->
    <script src="/static/js/skin.js"></script>
    <div class="select-skin">
        <div class="skin-btn">
            <a href="javascript:void(0);" class="skin-btn-open">换<br>肤</a>
        </div>

        <div class="skin-content">
            <h1>选择风格<span class="skin-close">关闭</span></h1>
            <div class="skin-content-list">
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('qingxin'); return false;" class="btn1">清新</a>
                </div>
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('jianyue'); return false;" class="btn2">简约</a>
                </div>
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('qingshuang'); return false;"
                                          class="btn3">清爽</a></div>
            </div>
        </div>
    </div>
</header>

web/templates/backup/link.html
{% extends "web/base.html" %}
{% block content %}
    <section class="mysection" style="animation: fuxiasuo 0.8s;">页面建设中。。。。</section>

{% endblock %}

web/templates/backup/message.html
<h3 class="form-btn blue-text"><a href="javascript:;"><i class="el-edit"></i>我要留言 / 展开表单</a></h3>
<div id="Coon" class="form-zd form-in">
    <div id="cloud-tie-wrapper" class="cloud-tie-wrapper"></div>
    <script>
        var cloudTieConfig = {
            url: "{{ source_url }}",
            sourceId: "{{ source_id }}",
            productKey: "0078b35005ba4b3da6403eb8d16b0bcb",
            target: "cloud-tie-wrapper"
        };
    </script>
    <script src="https://img1.cache.netease.com/f2e/tie/yun/sdk/loader.js"></script>

</div>

web/templates/backup/message_board.html
{% extends "web/base.html" %}

{% block content %}

    <section class="mysection">

        {% include "web/message.html" %}
    </section>

{% endblock %}

web/templates/backup/right.html
<aside class="myaside">
    <!--关注我-->
    <div class="focus-me bg-color animation-div">
        <h4 class="index-title"><i class="el-heart"></i>关注我
            <small>Focus Me</small>
        </h4>
        <div class="xiangguan">

            <div><a class="benbo" href="https://github.com/jhao104/django-blog" target="_blank"><i
                    class="el-download-alt"></i></a><span>博客源码</span></div>
            <div><a class="taobao"
                    href="https://my.oschina.net/jhao104/blog"
                    target="_blank"><i class="el-blogger"></i></a><span>博客地址</span></div>
            <div><a class="side-fx"><i class="el-share-alt"></i></a><span>分享本博</span></div>
            <div><a class="mail-btn" href="javascript:;"><i class="el-envelope"></i></a><span>订阅我</span></div>
        </div>

        <div class="mail-dy">
            <form action="#">
                <input type="hidden" name="t" value="qf_booked_feedback"/>
                <input type="hidden" name="id" value="b2b151b4bc010575c083e18e227ae907aac82bc47e84d3e0"/>
                <span>订阅</span>
                <input name="to" type="text" placeholder="输入邮箱点击订阅吧" onfocus="this.placeholder=''"
                       onblur="this.placeholder='输入邮箱点击订阅吧(暂无)'"/>
                <i class="el-envelope"><input value=" " type="submit"/></i>
            </form>
            <i class="el-remove fx-close"></i>
        </div>

        <div class="bd-fx side-bdfx ">
            <i class="el-remove fx-close"></i>
            <ul class="bdsharebuttonbox">
                <li><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></li>
                <li><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a></li>
                <li><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a></li>
                <li><a href="#" class="bds_tieba" data-cmd="tieba" title="分享到百度贴吧"></a></li>
            </ul>
            <script>window._bd_share_config = {
                "common": {
                    "bdSnsKey": {},
                    "bdText": "",
                    "bdMini": "2",
                    "bdMiniList": false,
                    "bdPic": "",
                    "bdStyle": "1",
                    "bdSize": "32"
                }, "share": {}
            };
            with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];</script>
        </div>
    </div>
    <!--最新更新-->

    <div class="clos-new bg-color animation-div">
        <h4 class="index-title"><i class="el-bulb"></i>最新资讯
            <small>Latest News</small>
        </h4>
        <ul>
            <li><i class="el-cloud"></i>
                <iframe id="tianqi" scrolling="no" frameborder="0" allowtransparency="true"
                        src="http://i.tianqi.com/index.php?c=code&id=40"></iframe>
            </li>

            <li><i class="el-calendar"></i>历史今天：
                <iframe src="http://www1.todayonhistory.com/code/6.html?w=250&h=20&bky=dotted&bks=0&fs=14&fc=#565656&hg=14&ie=0&xhx=none&sd=300&px=3&len=0&sk=1&n=0"
                        width="250" height="15" scrolling="no" frameborder="0" allowtransparency="true"></iframe>
            </li>
        </ul>
    </div>
    <!--搜索-->
    <div class="search animation-div">
        <form action="{% url "web:search" %}" method="get">
            <div class="search-index">
                <input name="key" type="text" placeholder="请输入关键字" onfocus="this.placeholder=''"
                       onblur="this.placeholder='请输入关键字'"/>
                <i class="el-search"><input value=" " type="submit"/></i>
            </div>
        </form>
    </div>

    <!--文章排行tab-->
    <div class="mytab bg-color animation-div">
        <div class="tab-btn"><a class="hd-btn tab-active" href="javascript:;"><i class="el-comment-alt"></i>最新评论</a><a
                class="ph-btn" href="javascript:;"><i class="el-signal"></i>文章排行</a></div>
        <ul class="hudong-ul">
            <!--=======查询相册=============-->
            {% for comment in comment_list %}
                <li>
                    <div class="sd-name">
                        <span><i class="el-book"></i>{{ comment.title }}</span>
                        <a class="blue-text" href="{{ comment.url }}" title="{{ comment.comment }}">{{ comment.comment }}</a>
                        <span style="text-align: right">— &nbsp;<i class="el-user"></i>{{ comment.user_name }}</span>
                    </div>
                </li>
            {% endfor %}


        </ul>
        <!--文章排行-->
        <ul class="paihang-ul">
            {% for article in article_rank %}
                <li><span></span><a href="{% url "web:detail" pk=article.id %}"
                                    title="{{ article.title }}">{{ article.title }}<b><i
                        class="el-eye-open"></i>({{ article.view }})</b></a></li>
            {% endfor %}
        </ul>

    </div>

    <!--标签-->
    <div class="cloud bg-color animation-div">
        <h4 class="index-title"><i class="el-tags"></i>标签云
            <small>Tags Clouds</small>
        </h4>
        <ul id="3dcloud">
            {% for tag in tag_list %}
                <li><a href="{% url "web:tag" name=tag.tag_name %}" title="标签：{{ tag.tag_name }} ">{{ tag.tag_name }}</a></li>
            {% endfor %}
        </ul>
    </div>


    <!--友情链接-->
    <div class="side-link animation-div">
        <h4 class="index-title"><i class="el-paper-clip"></i>友情链接
            <small>Friend Links</small>
            <a href="mailto:j_hao104@163.com?subject=博客友链互换&body=博客名称:<br> 博客描述:<br>博客地址:"><i class="el el-plus"></i>申请</a></h4>
        <ul>
            <li><a href="http://ws234.com/" target="_blank"
                   title="专注互联网，记录个人的学习生活，推荐实用软件和网站优化技巧，分享最新的网站技巧博客技巧，是一个多元化值得收藏的个人博客！">王商博客</a></li>
            <li><a href="https://www.zaoshu.io/" target="_blank" title="智能云爬虫">造数</a></li>
            <li><a href="http://brucedone.com/" target="_blank" title="大鱼的鱼塘 - 一个总会有收获的地方">大鱼的鱼塘</a></li>
            <li><a href="http://www.songluyi.com/" target="_blank" title="">灯塔水母</a></li>
            <li><a href="http://blog.topspeedsnail.com/" target="_blank" title="本博客专注于技术，Linux，编程，Python，C，Ubuntu、开源软件、Github等">斗大的熊猫</a></li>
            <li><a href="https://www.urlteam.org/" target="_blank" title="本博客专注于技术，Linux，编程，Python，C，Ubuntu、开源软件、Github等">URL-team</a></li>
        </ul>
    </div>
</aside>

web/templates/backup/search.html
{% extends "web/base.html" %}
{% load custom_filter %}
{% block content %}
    {% paginate article_list 8 %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "web:article" pk=0 %}"><i class="el-search"></i> 搜索到<b class="lable">{{ key }}</b>相关结果</a>
            <span class="orange-text">{{ category }}</span>
            <span style="float:right;margin-right:10px;">共:<a class="orange-text"> {{ count }} </a>条</span>
        </h4>
        <div class="arclist">
            <!--列表开始-->
            <ul>
                {% for article in article_list %}
                    <li {% if article.view > 500 %}id="tuijian"{% elif article.view > 100 %} id="Hot" {% endif %}>
                    <div class="arcimg">

                        <img src="{{ article.picture }}"
                             alt="{{ article.title }}" title="{{ article.title }}"/>
                    </div>
                    <div class="arc-right">
                        <h4 class="blue-text"><a href="{% url "web:detail" pk=article.id %}" title="{{ article.title }}">{{ article.title }}</a></h4>
                        <p>{{ article.digest }}</p>
                        <ul>
                            <li><a title="{{ article.author }} {{ article.date_time }} 发表 "><i class="el-time"></i> {{ article.date_time }}</a></li>
                            <li><a href="#" title="作者： {{ article.author }}"><i class="el-user"></i>{{ article.author }}</a></li>
                            <li><a href="#" title="已有 {{ article.comment }} 条评论"><i class="el-comment"></i>{{ article.comment }}</a>
                            </li>
                            <li><a title="已有 {{ article.view }} 次浏览"><i class="el-eye-open"></i>{{ article.view }}</a></li>
                            <li class="mob-hidden">
                                <i class="el-tag"></i>
                                <a href="#">{{ article.tag.values| getTag }}</a>&nbsp;
                            </li>
                            <li><a href="{% url "web:article" pk=article.category_id %}" title="查看分类"><i class="el-th-list"></i>{{ article.category }}</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <!--列表结束-->
        </div>
        <!--分页-->

        <div class="pagination">
            <div class="list-page">
                <ul class="post-data">
                    <li><a>第 {{ current_page }} - {{ last_page }} 页</a> <a>共 {{ count }} 条</a></li>
                </ul>
            </div>
            <ul>

                <li {% if current_page == 1 %}class="active"{% endif %}><a href="?page=1">首页</a></li>
                <li {% if current_page >= 2 %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:-1 }}">上一页</a></li>
                <li {% if current_page < last_page %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:1 }}">下一页</a></li>
                <li {% if current_page == last_page %}class="active"{% endif %}><a href="?page={{ last_page }}">尾页</a></li>
            </ul>
        </div>

    </section>

{% endblock %}

web/templates/backup/tag.html
{% extends "web/base.html" %}
{% load custom_filter %}
{% block content %}
    {% paginate article_list 8 %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "web:article" pk=0 %}"><i class="el-tag"></i> 标签<b class="lable">{{ tag }}</b></a>
            <span class="orange-text">{{ category }}</span>
            <span style="float:right;margin-right:10px;">共有:<a class="orange-text"> {{ count }} </a>篇</span>
        </h4>
        <div class="arclist">
            <!--列表开始-->
            <ul>
                {% for article in article_list %}
                    <li {% if article.view > 500 %}id="tuijian"{% elif article.view > 100 %} id="Hot" {% endif %}>
                    <div class="arcimg">

                        <img src="{{ article.picture }}"
                             alt="{{ article.title }}" title="{{ article.title }}"/>
                    </div>
                    <div class="arc-right">
                        <h4 class="blue-text"><a href="{% url "web:detail" pk=article.id %}" title="{{ article.title }}">{{ article.title }}</a></h4>
                        <p>{{ article.digest }}</p>
                        <ul>
                            <li><a title="{{ article.author }} {{ article.date_time }} 发表 "><i class="el-time"></i> {{ article.date_time }}</a></li>
                            <li><a href="#" title="作者： {{ article.author }}"><i class="el-user"></i>{{ article.author }}</a></li>
                            <li><a href="#" title="已有 {{ article.comment }} 条评论"><i class="el-comment"></i>{{ article.comment }}</a>
                            </li>
                            <li><a title="已有 {{ article.view }} 次浏览"><i class="el-eye-open"></i>{{ article.view }}</a></li>
                            <li class="mob-hidden">
                                <i class="el-tag"></i>
                                <a href="#">{{ article.tag.values| getTag }}</a>&nbsp;
                            </li>
                            <li><a href="{% url "web:article" pk=article.category_id %}" title="查看分类"><i class="el-th-list"></i>{{ article.category }}</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <!--列表结束-->
        </div>
        <!--分页-->

        <div class="pagination">
            <div class="list-page">
                <ul class="post-data">
                    <li><a>第 {{ current_page }} - {{ last_page }} 页</a> <a>共 {{ count }} 条</a></li>
                </ul>
            </div>
            <ul>

                <li {% if current_page == 1 %}class="active"{% endif %}><a href="?page=1">首页</a></li>
                <li {% if current_page >= 2 %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:-1 }}">上一页</a></li>
                <li {% if current_page < last_page %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:1 }}">下一页</a></li>
                <li {% if current_page == last_page %}class="active"{% endif %}><a href="?page={{ last_page }}">尾页</a></li>
            </ul>
        </div>

    </section>

{% endblock %}